<?php
  // PAGE TEXT

  $xmlicon_titletext              = "Get data in XML format";   // Text displayed when hovering xml-icon
  $serverselecttext               = "Change server view";

  // Output text

  $output_service_on              = "installed";
  $output_service_off             = "not installed"; 

  $output_service_unknown         = "unknown";
  $output_service_available       = "available";
  $output_service_notavailable    = "not available";

  $output_service_connected       = "success";
  $output_service_notconnected    = "unable";
  $output_service_notpossible     = "pass";

  $output_service_loggedin        = "accepted";
  $output_service_notloggedin     = "refused";

  // Services not available
  
  $service_notinstalled           = "not running on this server";
  $service_notconfigured          = "not yet configured";
  $service_filenotresolving       = "global path to file not resolving in local DNS";
  $service_filenotexist           = "file not found";

  // Table headline text

  $th_service                     = "service";
  $th_state                       = "state";
  $th_version                     = "version";
  $th_result                      = "result";
  $th_details                     = "details";

  // Errors

  $error_mysqldbnotconnected      = "Could not connect to MySQL Database: " . $mysql_address;
  $error_mysqldbopen              = "Connected to MySQL Database: " . $mysql_address . ", but failed to open database: " . $mysql_dbname;

  $xmloutput_disabled             = "XML output disabled by admin";

?>
