<?php

      $alternatemodulesarray[] = "";

      $alternatemodulesarray["ASP"] = array(
       "state"      => $aspcomponentScriptEngine,
       "details"    => $aspcomponentScriptEnginev,
       "alternate"    => $aspcomponentScriptEnginea
        );

      $alternatemodulesarray["Gateway Interface"] = array(
       "state"      => $aspcomponentGatewayInterface,
       "details"    => $aspcomponentGatewayInterfacev,
       "alternate"    => $aspcomponentGatewayInterfacea
        );

      $alternatemodulesarray["ScriptTimeout"] = array(
       "state"      => $aspcomponentServerScriptTimeout,
       "details"    => $aspcomponentServerScriptTimeoutv,
       "alternate"    => $aspcomponentServerScriptTimeouta
        );

      $alternatemodulesarray["Locale"] = array(
       "state"      => $aspcomponentLocaleID,
       "details"    => $aspcomponentLocaleIDv,
       "alternate"    => $aspcomponentLocaleIDa
        );

      $alternatemodulesarray["W3 Image"] = array(
       "state"      => $aspcomponentw3Image,
       "details"    => $aspcomponentw3Imagev,
       "alternate"    => $aspcomponentw3Imagea
        );

      $alternatemodulesarray["W3 upload"] = array(
       "state"      => $aspcomponentw3upload,
       "details"    => $aspcomponentw3uploadv,
       "alternate"    => $aspcomponentw3uploada
        );

      $alternatemodulesarray["W3 JMail"] = array(
       "state"      => $aspcomponentw3JMail,
       "details"    => $aspcomponentw3JMailv,
       "alternate"    => $aspcomponentw3JMaila
        );

      $alternatemodulesarray["ASP SmartUpload"] = array(
        "state"      => $aspcomponentASPSmartUpload,
       "details"    => $aspcomponentASPSmartUploadv,
       "alternate"    => $aspcomponentASPSmartUploada
        );

      $alternatemodulesarray["ASP Image"] = array(
       "state"      => $aspcomponentASPImage,
       "details"    => $aspcomponentASPImagev,
       "alternate"    => $aspcomponentASPImagea
        );

      $alternatemodulesarray["ASP svgMailer"] = array(
       "state"      => $aspcomponentASPMail,
       "details"    => $aspcomponentASPMailv,
       "alternate"    => $aspcomponentASPMaila
        );

      $alternatemodulesarray["JRO JetEngine"] = array(
       "state"      => $aspcomponentJROJetEngine,
       "details"    => $aspcomponentJROJetEnginev,
       "alternate"    => $aspcomponentJROJetEnginea
        );

      $alternatemodulesarray["W3 NetUtils"] = array( 
       "state"      => $aspcomponentNetUtils,
       "details"    => $aspcomponentw3NetUtilsv,
       "alternate"    => $aspcomponentw3NetUtilsa
        );

      $alternatemodulesarray["W3 INFO"] = array(
       "state"      => $aspcomponentw3info,
       "details"    => $aspcomponentw3infov,
       "alternate"    => $aspcomponentw3infoa
        );

      $alternatemodulesarray["W3 SiteTree"] = array(
       "state"      => $aspcomponentw3SiteTree,
       "details"    => $aspcomponentw3SiteTreev,
       "alternate"    => $aspcomponentw3SiteTreea
        );

      $alternatemodulesarray["Persits Email"] = array(
       "state"      => $aspcomponentAspemail,
       "details"    => $aspcomponentAspemailv,
       "alternate"    => $aspcomponentAspemaila
        );

      $alternatemodulesarray["Persits XUpload"] = array(
       "state"      => $aspcomponentXUpload,
       "details"    => $aspcomponentXUploadv,
       "alternate"    => $aspcomponentXUploada
        );

      $alternatemodulesarray["MSXML3"] = array(
       "state"      => $aspcomponentMSXML3,
       "details"    => $aspcomponentMSXML3v,
       "alternate"    => $aspcomponentMSXML3a
        );

      $alternatemodulesarray["MSXML4"] = array(
       "state"      => $aspcomponentMSXML4,
       "details"    => $aspcomponentMSXML4v,
       "alternate"    => $aspcomponentMSXML4a
        );

      $alternatemodulesarray["Hex Icmp"] = array(
       "state"      => $aspcomponentHexIcmp,
       "details"    => $aspcomponentHexIcmpv,
       "alternate"    => $aspcomponentHexIcmpa
        );

      $alternatemodulesarray["Hex Lookup"] = array(
       "state"      => $aspcomponentHexLookup,
       "details"    => $aspcomponentHexLookupv,
       "alternate"    => $aspcomponentHexLookupa
        );

      $alternatemodulesarray["Hex TcpQuery"] = array(
       "state"      => $aspcomponentHexTcpQuery,
       "details"    => $aspcomponentHexTcpQueryv,
       "alternate"    => $aspcomponentHexTcpQuerya
        );

      $alternatemodulesarray["Hex ValidEmail"] = array(
       "state"      => $aspcomponentEmailConnection,
       "details"    => $aspcomponentEmailConnectionv,
       "alternate"    => $aspcomponentEmailConnectiona
        );












?>
