<?php

      $alternatemodulesarray[] = "";
      
      $alternatemodulesarray[".NET"] = array(
         "details"    => $aspxcomponentversionv,
         "state"      => $aspxcomponentversion,
         "alternate"    => $aspxcomponentversiona
        );

      $alternatemodulesarray["Server Uptime"] = array(
         "details"    => $aspxcomponentUptimev,
         "state"      => $aspxcomponentUptime,
         "alternate"    => $aspxcomponentUptimea
        );

      $alternatemodulesarray["Processors"] = array(
         "details"    => $aspxcomponentProcessorCountv,
         "state"      => $aspxcomponentProcessorCount,
         "alternate"    => $aspxcomponentProcessorCounta
        );

      $alternatemodulesarray["Working Set"] = array(
         "details"    => $aspxcomponentWorkingSetv,
         "state"      => $aspxcomponentWorkingSet,
         "alternate"    => $aspxcomponentWorkingSeta
        );
        
      $alternatemodulesarray[".NET Web User"] = array(
         "details"    => $aspxcomponentuserv,
         "state"      => $aspxcomponentuser,
         "alternate"    => $aspxcomponentusera
        );

      $alternatemodulesarray["Machine Name"] = array(
         "details"    => $aspxcomponentMachineNamev,
         "state"      => $aspxcomponentMachineName,
         "alternate"    => $aspxcomponentMachineNamea
        );

      $alternatemodulesarray["System Directory"] = array(
         "details"    => $aspxcomponentSystemDirectoryv,
         "state"      => $aspxcomponentSystemDirectory,
         "alternate"    => $aspxcomponentSystemDirectorya
        );

?>
