<?php

      $modulesarray[] = "";

      $modulesarray["PHP"] = array(
       "state"      => $strphpversion,
       "version"    => $strphpversionv,
       "alternate"  => $strphpversiona
      );

      $modulesarray["Server platform"] = array(
       "state"      => $strphpserverplatform,
       "version"    => $strphpserverplatformv,
       "alternate"  => $strphpserverplatforma
      );
  
      $modulesarray["Register Globals"] = array(
       "state"      => $strphpregglobal,
       "version"    => $strphpregglobalv,
       "alternate"  => $strphpregglobala
      );

      $modulesarray["Safe mode"] = array(
       "state"      => $strphpsafemode,
       "version"    => $strphpsafemodev,
       "alternate"  => $strphpsafemodea
      );
  
      $modulesarray["Magic Quotes"] = array(
       "state"      => $strphpmagicquotes, 
       "version"    => $strphpmagicquotesv,
       "alternate"  => $strphpmagicquotesa
      );

      $modulesarray["Zend Engine"] = array(
       "state"      => $strphpzend, 
       "version"    => $strphpzendv,
       "alternate"  => $strphpzenda
      );

      $modulesarray["Curl"] = array(
       "state"      => $strphpcurl, 
       "version"    => $strphpcurlv,
       "alternate"  => $strphpcurla
      );

      $modulesarray["GDlib"] = array(
       "state"      => $strphpgdlib, 
       "version"    => $strphpgdlibv,
       "alternate"  => $strphpgdliba
      );

      $modulesarray["PDFlib"] = array(
       "state"      => $strphppdflib, 
       "version"    => $strphppdflibv,
       "alternate"  => $strphppdfliba
      );

      $modulesarray["exif"] = array(
       "state"      => $strphpexif, 
       "version"    => $strphpexifv,
       "alternate"  => $strphpexifa
      );

      $modulesarray["openssl"] = array(
       "state"      => $strphpopenssl, 
       "version"    => $strphpopensslv,
       "alternate"  => $strphpopenssla
      );

      $modulesarray["tidy HTML"] = array(
       "state"      => $strphptidy, 
       "version"    => $strphptidyv,
       "alternate"  => $strphptidya
      );

      $modulesarray["SimpleXML"] = array(
       "state"      => $strphpsimplexml, 
       "version"    => $strphpsimplexmlv,
       "alternate"  => $strphpsimplexmla
      );

      $modulesarray["DOM/XML API"] = array(
       "state"      => $strphpdom, 
       "version"    => $strphpdomv,
       "alternate"  => $strphpdoma
      );

      $modulesarray["libXML"] = array(
       "state"      => $strphplibxml, 
       "version"    => $strphplibxmlv,
       "alternate"  => $strphplibxmla
      );

      $modulesarray["XLS/EXSLT"] = array(
       "state"      => $strphplibxsl, 
       "version"    => $strphplibxslv,
       "alternate"  => $strphplibxsla
      );

      $modulesarray["XML-RPC"] = array(
       "state"      => $strphpxmlrpc, 
       "version"    => $strphpxmlrpcv,
       "alternate"  => $strphpxmlrpca
      );

      $modulesarray["ImageMagick"] = array(
       "state"      => $strphpImageMagick, 
       "version"    => $strphpImageMagickv,
       "alternate"  => $strphpImageMagicka
      );

      $modulesarray["imap"] = array(
       "state"      => $strphpimapext, 
       "version"    => $strphpimapextv,
       "alternate"  => $strphpimapexta
      );

      $modulesarray["mysqli"] = array(
       "state"      => $strphpmysqliinfo, 
       "version"    => $strphpmysqliinfov,
       "alternate"  => $strphpmysqliinfoa
      );

      $modulesarray["pcre"] = array(
       "state"      => $strphppcre, 
       "version"    => $strphppcrev,
       "alternate"  => $strphppcrea
      );

      $modulesarray["json support"] = array(
       "state"      => $strphpjson, 
       "version"    => $strphpjsonv,
       "alternate"  => $strphpjsona
      );

      $modulesarray["iconv"] = array(
       "state"      => $strphpiconv, 
       "version"    => $strphpiconvv,
       "alternate"  => $strphpiconva
      );

      $modulesarray["mcrypt"] = array(
       "state"      => $strphpmcrypt, 
       "version"    => $strphpmcryptv,
       "alternate"  => $strphpmcrypta
      );

      $modulesarray["zlib"] = array(
       "state"      => $strphpzlib, 
       "version"    => $strphpzlibv,
       "alternate"  => $strphpzliba
      );

      $modulesarray["zip"] = array(
       "state"      => $strphpzip, 
       "version"    => $strphpzipv,
       "alternate"  => $strphpzipa
      );

      $modulesarray["bz2"] = array(
       "state"      => $strphpbz2, 
       "version"    => $strphpbz2v,
       "alternate"  => $strphpbz2a
      );

      $modulesarray["SQLite"] = array(
       "state"      => $strphpsqlite, 
       "version"    => $strphpsqlitev,
       "alternate"  => $strphpsqlitea
      );

      $modulesarray["ADOdb"] = array(
       "state"      => $strphpadodb, 
       "version"    => $strphpadodbv,
       "alternate"  => $strphpadodba
      );

      $modulesarray["svn"] = array(
       "state"      => $strphpsvn, 
       "version"    => $strphpsvnv,
       "alternate"  => $strphpsvna
      );

      $modulesarray["geoip"] = array(
       "state"      => $strphpgeoip, 
       "version"    => $strphpgeoipv,
       "alternate"  => $strphpgeoipa
      );

      $modulesarray["ps"] = array(
       "state"      => $strphpps, 
       "version"    => $strphppsv,
       "alternate"  => $strphppsa
      );

      $modulesarray["sysvmsg"] = array(
       "state"      => $strphpsysvmsg, 
       "version"    => $strphpsysvmsgv,
       "alternate"  => $strphpsysvmsga
      );



?>
